### ISSUE TITLE
مشاهده تاریخ انقضا کانفیگ 

### ISSUE THREAD

**Issue by Nima786** [TeleDark/v2ray-tel-bot#15]
سلام، میشه قابلیت اضافه شدن تاریخ انقضا کانفیگ ها رو هم اضافه کنید؟ چون این هم خیلی کاربردی هست که کاربر بدونه چه موقع کانفیگش مهلتش تموم میشه.

**Comment by Nima786** [comment]
بله دقیقاً همینی که شما گفتید. ممنون

**Comment by TeleDark** [comment]
سلام وقت بخیر
اضافه شد

**Comment by TeleDark** [comment]
اضافه شد 
دستور زیر رو بزنید تا سورس جدید برنامه رو بگیره

cd && rm -rf v2ray-tel-bot && git clone
https://github.com/TeleDark/v2ray-tel-bot.git && cd v2ray-tel-bot/ && pip
install -r requirements.txt

 و بعد فایل keys و login رو مجدد ادیت کنید
موفق باشید
