### ISSUE TITLE
پنل ثنایی و علیرضا

### ISSUE THREAD

**Issue by sirvan32** [TeleDark/v2ray-tel-bot#16]
سلام ممنون بابت ربات عالی و زحماتی که کشیدی 
فقط برای پنل ثنایی و پنل علیرضا که قابلیت مولتی یوزر رو یه پورت دارن هر بار که ای دی رو سرچ میکنی رو ربات، اطلاعات دو کانفیگ پایین تر خودشو خروجی میده

**Comment by TeleDark** [comment]
بله درسته ولی رفع شده این مشکل دستور زیر رو بزنید و مراحل رو دوباره برید
cd && rm -rf v2ray-tel-bot && git clone
https://github.com/TeleDark/v2ray-tel-bot.git && cd v2ray-tel-bot/ && pip
install -r requirements.txt

 و بعد فایل keys و login رو مجدد ادیت کنید
موفق باشید

**Comment by sirvan32** [comment]
متاسفانه همچنان مشکل برقرار است.

https://s6.uupload.ir/files/1_l021.png

**Comment by TeleDark** [comment]
یه فایل تو مسیر
/etc/x-ui/x-ui.db
هست
لطفا برام بفرستینش
برای رفع باگ نیاز نیشه

**Comment by sirvan32** [comment]
https://www.uplooder.net//files/4f0e77939b334d7132da7afd64d38839/x-ui.zip.html

**Comment by TeleDark** [comment]
بررسی کردم درست بود!
دقیقا همون کانفیگی که تو عکس گفتین
![image](https://user-images.githubusercontent.com/46258401/231546452-0a46da59-fcfb-4072-a630-cb138a14e167.png)

بنظرم سورس رو بروز نکردین
یا فایل login رو داخل کرون تب نگفتین هر چندقه اجرا بشه

**Comment by sirvan32** [comment]
سپاس گذارم بله لینک رو اشتبایی تو کرون تب چایگزین کرده بودم.همه چی عالی کار میکنه ممنون بابت زحماتت.یه پیشنهاد هم بدم اگه با کانفیگ هم کارکنه عالی میشه .منظورم اینه هم با uidd هم با خود کانفیگ
بازم ممنون

**Comment by TeleDark** [comment]
بله از قبل uuid پورت و remark اضاف شده برای گرفتن اطلاعات 
سعی میکنم امشب به سورس اصلی اضافش کنم
