### ISSUE TITLE
 incorrect URL or port number

### ISSUE THREAD

**Issue by sadeghmolaei** [TeleDark/v2ray-tel-bot#19]
سلام 
هرچی ادرس و پورت میزنم ارور https:/yahoo.com:1020/ ➜ incorrect URL or port number
میگیرم

**Comment by TeleDark** [comment]
ایپی میدین یا دامین؟
SSL تون درست هست؟
پورتو درست میدین؟

**Comment by sadeghmolaei** [comment]
دامنه با پورت همراه https میزنم همه چیز و دقیقا درست میزنم روی چنتا سرور تست کردم 
debian 11
 در صورت امکان ای دی تلگرام بدید برای تست

**Comment by sirvan32** [comment]
https رو کلود این پورت رو ساپورت نمیکنه 
من با ریورس پروکسی ترافیک رو انتقال میدم رو پورت 443 و مشکل ندارم 5 سرور رو وصل کردم

**Comment by sadeghmolaei** [comment]
این مشکل و حل کردم ولی بعد از یک بار اجرای bot.py و ریبوت سرور دیگه کار نمیکنه و خطا در فایل های برنامه میده crontab هم درست کار نمیکنه

**Comment by TeleDark** [comment]
بعد از زدن دستور crontab -e مطمئن بشید این خط رو اضاف کردید

@reboot python3 /root/v2ray-tel-bot/bot.py

اگر این خط وجود داشت اما بعد از ریبوت سرور کار نمیکرد دوتا فایل login.py و bot.py رو باز کنید و این کارکتر( ➜ ) رو از داخلش حذف کنید احتمالا نسخه سرورس که نصب دارین سرویس کرون انکدش لاتین هست

**Comment by sadeghmolaei** [comment]
python3 login.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/v2ray-tel-bot/login.py", line 120, in <module>
    login()
  File "/root/v2ray-tel-bot/login.py", line 60, in login
    if response.json()['success']:
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sadeghmolaei** [comment]
python3.9  پاک کردم و python3.10 نصب کردم تمام requirements به درستی نصب شد یک بار اجرا میشه کار میکنه بعد از ریبوت سرور دیگه کار نمیکنه و خطای زیر را میده

python3.10 login.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/v2ray-tel-bot/login.py", line 120, in <module>
    login()
  File "/root/v2ray-tel-bot/login.py", line 60, in login
    if response.json()['success']:
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sadeghmolaei** [comment]
در فایل login.py خط 20 
#     'pass_panel': 'admin'
یک کاما جا افتاده اصلاح کنید

**Comment by sadeghmolaei** [comment]
من مشکلم با این روش بر روی Debian 11 و پنل 3x-ui v1.2.3 بر طرف شد.


apt update -y
apt install git python3 python3-pip tmux -y
-----------------------------
git clone https://github.com/TeleDark/v2ray-tel-bot.git && cd v2ray-tel-bot
-----------------------------
pip install -r requirements.txt
-----------------------------
chmod +x *.py
-----------------------------
vim login.py
python3 login.py
-----------------------------
vi keys.py
-----------------------------
vi /etc/crontab
@reboot root /bin/bash /root/scripts/x-ui-restart.sh >/dev/null 2>&1
*/5 * * * * root /bin/bash /root/scripts/login.sh >/dev/null 2>&1
-----------------------------
mkdir /root/scripts/
-----------------------------
vi /root/scripts/x-ui-restart.sh
#!/bin/bash
sleep 5
x-ui restart
sleep 5
/usr/bin/tmux new -d -s python 'python3 /root/v2ray-tel-bot/bot.py'
-----------------------------
vi /root/scripts/login.sh
#!/bin/bash
sleep 10
python3 /root/v2ray-tel-bot/login.py
-----------------------------
chmod +x /root/scripts/*.sh

**Comment by TeleDark** [comment]
خط ۲۰ کامنت هست و جدا از کامنت بودن، ایندکس آخر متغیر dict نیاز به کاما نداره
