### ISSUE TITLE
ارور نصب

### ISSUE THREAD

**Issue by eleyanr** [TeleDark/v2ray-tel-bot#20]
سلام برای من موقع نصب requistment .txt ارور میده
ould not find a version that satisfies the requirement anyio==3.6 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for anyio==3.6.2 (from -r requirements.txt (line 1))

چیکار کنم ممنون میشم یه ایدی تلگرام یا چیزی بدی کمکم کنی

**Comment by TeleDark** [comment]
نسخه پایتونی که رو سرورتون هست قدیمی تره یا احتمالا pip داره از نسخه قدیمی تر پایتونی که نصب دارین استفاده میکنه
بنظرم با این دستور حل بشه

apt update && apt install python3.10 -y && python3 -m pip install --upgrade pip && python3 -m pip install -r /root/v2ray-tel-bot/requirements.txt && python3 -m pip install --upgrade setuptools

**Comment by eleyanr** [comment]
شرمنده من دوباره پیام دادم الان این ارور بهم میده 

ERROR: Could not find a version that satisfies the requirement charset-normalizer==3.1.0 (from versions: 0.1a0, 0.1.1a0, 0.1.2b0, 0.1.4b0, 0.1.5b0, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.4.0, 1.4.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.1.0, 2.1.1, 3.0.0b1, 3.0.0b2, 3.0.0rc1, 3.0.0, 3.0.1)
ERROR: No matching distribution found for charset-normalizer==3.1.0

**Comment by TeleDark** [comment]
دستور زیر رو بزنید لطفا
```
bash <(curl -Ls https://raw.githubusercontent.com/TeleDark/v2ray-tel-bot/main/install.sh)
```
