### ISSUE TITLE
مشکل در نمایش تاریخ انقضا

### ISSUE THREAD

**Issue by kooshamostofi** [TeleDark/v2ray-tel-bot#21]
با سلام و تشکر بابت زحمات شما. من روی 2 تا پنل این ربات رو نصب کردم بدون مشکل. روی پنل اول که همون پنل پینی هست مشکلی وجود نداره و همه چیز عالیست. اما پنل دوم که پنل سنایی هست زمان اکانت را بینهایت نشون میده.
![Capture](https://user-images.githubusercontent.com/130854017/232235006-5ac1a957-1672-4547-b650-f3bed5893744.PNG)

امکانش وجود داره که این مشکل حل بشه؟ ممنونم از لطف شما

**Comment by sirvan32** [comment]
تو فایل لاگین اول ادرس پنل ثنایی رو بزن بعد پنل چینی.یعنی صفحه ورود به پنل ثنایی باید بالا باشه

**Comment by kooshamostofi** [comment]
ممنون از پیگیری و پاسختون. بله از ابتدا به همین شکلی که میفرمایید تنظیم کردم و با این مشکل روبرو شدم

**Comment by kooshamostofi** [comment]
![image](https://user-images.githubusercontent.com/130854017/232441579-c727f5cb-9d23-4a81-82b1-bc75c3de117b.png)

**Comment by TeleDark** [comment]
لطفا فایلی که تومسیر زیر هست
/etc/x-ui/x-ui.db
رو به تلگرام ایدی teledark ارسال کنید

**Comment by TeleDark** [comment]
بخاطر این بود که نام رو بر اساس uuid قرار میدادن و این مشکل پیش میومد
