### ISSUE TITLE
باگ های ربات

### ISSUE THREAD

**Issue by Mehdinaghipoor** [TeleDark/v2ray-tel-bot#23]
سلام خسته نباشی من ربات رو دیشب نصب کردم و راه اندازی شد فقط یه باگ داره و یک مورد هم خواستم ازش تغییر بدم که اگه میشه راهنمایی کنی باگش اینه که وقتی لینکی غیرفعال میشه تغییر وضعیتش نمیده و لینکی هم که خودش فعال هست رو گاها میزنه غیر فعال موردی هم که خواستم راهنمایی کنی اینه که من میخوام به جای اینکه uuid رو از کاربر بگیره remark رو بگیره و اطلاعات رو نشون بده چون ما تعداد کاربر ها بالا است و چندتا پنل هستن بهشون کد اشتراک میدیم و چون خیلیاشون زیاد اشنایی ندارن همون کد اشتراک رو وارد کنن از یک جنبه ای دیگه هم خواستم که کد اشتراکشون رو بزارم جای uuid که ربات شناساییشون نکرد ممنون میشم راهنمایی کنی

**Comment by TeleDark** [comment]
لطفا فایل موجود در مسیر زیر رو تلگرام به ایدی teledark بفرستید
/etc/x-ui/x-ui.db

**Comment by Mehdinaghipoor** [comment]
ارسال شده داداش

**Comment by TeleDark** [comment]
مشکل بخاطر این بود که uuid رو از حالت دیفالت x-ui تغیر دادن
