### ISSUE TITLE
ورژن

### ISSUE THREAD

**Issue by sinahinson** [TeleDark/v2ray-tel-bot#24]
درود خسته نباشید مهندس عزیز
ایا ربات با پنل اقای حسین سنائی کار میکند؟
و اینکه پورت پنل باید چند باشه؟ یا دلبخواه میشه تنظیم کرد

**Comment by TeleDark** [comment]
ممنونم سلامت باشید
خیر مشکلی نیس تا این لحظه...
میتونین داخل [یوتیوب](https://www.youtube.com/@teledark) ویدیو setup ربات رو ببینید
