### ISSUE TITLE
ارور ربات

### ISSUE THREAD

**Issue by eleyanr** [TeleDark/v2ray-tel-bot#26]
سلام من پنلم حسینی و برای ساخت اکانت برای کاربرا از tls استفاده میکنم حالا وقتی id یا uuid میزنم میزنه اطلاعات کاربر پیدا نشد من تانل زدم توی سرور خارج اکانت میسازم بعد به دامین سرور ایران تغییر میدم کاربر اول اطلاعات میده همه بینهایت میزنه بقیه کاربرا اطلاعات نمیده 

📍اطلاعات اکانت شما پیدا نشد! 
 مطمئنید ID رو درست وارد کردین؟ 
 اگه نمیدونین چجوری آیدی رو بدست بیارین رو /what بزنید... 
  نسبت به اینکه چه نرم افزاری نصب دارین به شما کمک میکنم.

همش این ارور میده

**Comment by TeleDark** [comment]
لطفا ربات رو اپدیت کنید
یا ویدیو یوتیوب رو تماشا کنید
