### ISSUE TITLE
اضافه کردن نسخه داکر

### ISSUE THREAD

**Issue by prxpostern** [TeleDark/v2ray-tel-bot#27]
سلام .

پنل من مسیر هم دارد. چگونه اون رو تعریف کنم. مثال میزنم

http://127.0.0.1:5623/myxui99

ممنون میشم راهنمایی فرمایید .

**Comment by amirh-web** [comment]
همون مسیر رو به همراه / اخر داخل سورس قرار بده

**Comment by prxpostern** [comment]
متشکرم

اگر بصورت داکر هم ارائه میدادید چقدر عالی میشد.

**Comment by TeleDark** [comment]
نسخه داکر اضاف شد
