### ISSUE TITLE
problem in install bot

### ISSUE THREAD

**Issue by mohamad-d** [TeleDark/v2ray-tel-bot#33]
hi
thanks for your bot
I watched your tutorial on YouTube and followed all the steps as in the video, but the bot does not work
my os is debian 11 and my python version is 3.10.0
my log is:

bash <(curl -Ls https://raw.githubusercontent.com/TeleDark/v2ray-tel-bot/main/install.sh)
Upgrade script...

Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease                                                
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease                                                               
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease                                                             
Ign:5 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu lunar InRelease                                  
Err:6 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu lunar Release                                    
  404  Not Found [IP: 185.125.190.52 80]
Hit:7 https://packagecloud.io/ookla/speedtest-cli/debian bullseye InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu lunar Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Python 3.10 is already installed 

/dev/fd/63: line 37: python3: command not found
curl: (23) Failure writing output to destination
/dev/fd/63: line 38: python3: command not found
Cloning into 'v2ray-tel-bot'...
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 181 (delta 30), reused 23 (delta 9), pack-reused 112
Receiving objects: 100% (181/181), 353.27 KiB | 786.00 KiB/s, done.
Resolving deltas: 100% (98/98), done.
Collecting PyYAML
  Using cached PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
Installing collected packages: PyYAML
Successfully installed PyYAML-6.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: anyio==3.6.2 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 1)) (3.6.2)
Requirement already satisfied: autopep8==2.0.2 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: beautifulsoup4==4.12.0 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 3)) (4.12.0)
Requirement already satisfied: certifi==2022.12.7 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 4)) (2022.12.7)
Requirement already satisfied: charset-normalizer==3.1.0 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 5)) (3.1.0)
Requirement already satisfied: h11==0.14.0 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 6)) (0.14.0)
Requirement already satisfied: httpcore==0.16.3 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 7)) (0.16.3)
Requirement already satisfied: httpx==0.23.3 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 8)) (0.23.3)
Requirement already satisfied: idna==3.4 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 9)) (3.4)
Requirement already satisfied: persiantools==3.0.1 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 10)) (3.0.1)
Requirement already satisfied: pycodestyle==2.10.0 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 11)) (2.10.0)
Requirement already satisfied: python-telegram-bot==20.2 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 12)) (20.2)
Requirement already satisfied: pytz==2023.2 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 13)) (2023.2)
Requirement already satisfied: PyYAML==6.0 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 14)) (6.0)
Requirement already satisfied: requests==2.28.2 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 15)) (2.28.2)
Requirement already satisfied: rfc3986==1.5.0 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 16)) (1.5.0)
Requirement already satisfied: sniffio==1.3.0 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 17)) (1.3.0)
Requirement already satisfied: soupsieve==2.4 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 18)) (2.4)
Requirement already satisfied: tomli==2.0.1 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 19)) (2.0.1)
Requirement already satisfied: urllib3==1.26.15 in /usr/local/lib/python3.10/site-packages (from -r /root/v2ray-tel-bot/requirements.txt (line 20)) (1.26.15)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (2.28.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests) (2022.12.7)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Edit 'config.yml' file, then restart the server with the 'reboot' command. The bot will start working after the server comes back up.

**Comment by mohamad-d** [comment]
Hi
Plz checking this issue 
Tnx

**Comment by TeleDark** [comment]
فیکس شد این مشکل
