### ISSUE TITLE
جوین اجباری چنل اصلی

### ISSUE THREAD

**Issue by sedddigh** [TeleDark/v2ray-tel-bot#38]
سلام خسته نباشید ممنون بابت طراحی ربات کاربردی شما
اگه امکانش هست موقعه ای که کاربر وارد روبات میشه اول عضو یک کانال بشه تا بتونه از روبات استفاده کنه. تشکر

**Comment by TeleDark** [comment]
سلام ممنونم 
اضاف شد
کلا پوشه ربات رو با دستور 
rm -rf ~/v2ray-tel-bot
پاک کنید
و داخل فایل config قسمت channel_id آیدی عددی کانالی که میخواین کاربر اجبار به جوین شدن بشه رو قرار بدین

**Comment by TeleDark** [comment]
کلا پوشه ربات رو با دستور
rm -rf ~/v2ray-tel-bot
پاک کنید
و داخل فایل config قسمت channel_id آیدی عددی کانالی که میخواین کاربر اجبار به جوین شدن بشه رو قرار بدین
