### ISSUE TITLE
مشکل با پنل NidukaAkalank

### ISSUE THREAD

**Issue by ir00ni** [TeleDark/v2ray-tel-bot#39]
بنظر میاد با پنل NidukaAkalank نسخه 1.6.4 همخوانی نداره
چون فقط اطلاعات یوزر ای دی 1 اونم فقط بر اساس کانفیگ نمایش میده
البته تو نمایش اطلاعات هم مقدار دانلود و آپلود و مصرف  را 0B نمایش میده

**Comment by TeleDark** [comment]
متاسفانه برنامه با این پنل همخوانی نداره
