### ISSUE TITLE
عدم نمایش اطلاعات بروز اکانت

### ISSUE THREAD

**Issue by Assoudeh-h** [TeleDark/v2ray-tel-bot#42]
با عرض سلام، خداقوت مهندس
از صبح امروز ربات اطلاعات اکانت رو اصلا بروزرسانی نمی کنه و اطلاعاتی که میاره اصلا اطلاعات بروز اکانت نیست
چیکار کنم؟ چرا این مشکل پیش اومده؟

**Comment by uzer0098** [comment]
یکبار سرورت رو ریبوت کن
