### ISSUE TITLE
مشکل بعد از ۴ تا url

### ISSUE THREAD

**Issue by alifathipor** [TeleDark/v2ray-tel-bot#43]
من ۴ تا سرور رو به خوبی میخونه ولی ۵ تا دیگه رو کلا نمیخونه
حساس میکنم کلا ۴ تا url قبول می کنه
محدودیت گذاشتین؟

**Comment by TeleDark** [comment]
وقتتون بخیر
خیر مشکلی نیس لطفا ربات رو بروزرسانی کنید
مشکلتون حل نشد تلگرام به ایدی tcledark پیام بدین بررسی کنم
