### ISSUE TITLE
عدم اتصال به آخرین آپدیت پنل سنایی

### ISSUE THREAD

**Issue by S0R0SH** [TeleDark/v2ray-tel-bot#48]
سلام دوست عزیز ، من همیشه از بات شما استفاده میکنم. یه سرور جدید راه اندازی کردم دیروز و پنل سنایی رو نصب کردم. متوجه شدم با آخرین ورژن پنل سنایی بات نمیتونه لوگین کنه با اینکه با همین مشخصات با ورژن پایینتر سنایی روی سرور های دیگه ام ربات به درست ی داره کار میکنه. حالا نمیدونم کجای پنل سنایی عوض شده که بات نمیتونه لوگین کنه. من یکم فایل لوگین رو عوض کردم قسمت سنایی رو ولی بازم نتونستم لاگین کنم به پنل. میتونم ورژن های قدیمی سنایی رو نصب کنم اما حیف هست این ربات خیلی سب ک هست دوست داشتم با همین کار کنم. امکانش هست بررسی بفرمایید ؟ ممنون میشم 
اینها روهم امتحان کردم: ipv4 و ipv6 - همچنین http یا بدون اون - عوض ک ردن یا پاک کردن list و پورت پنل و ... حقیقت دیگه ساده ترین کارایی که میشه کرد اینا بودن🙏🙏🙏🙏

**Comment by TeleDark** [comment]
لطفا ربات رو اپدیت کنید
