### ISSUE TITLE
ایراد جزیی

### ISSUE THREAD

**Issue by Shm9220** [TeleDark/v2ray-tel-bot#50]
دوتا ایراد جزیی تو ربات هس که اگه برطرف بشه خوبه . 

یکی اینکه وقتی اکانتی رو شارژ میکنیم و میزنیم مثلا از لحظه شروع ۳۰ روز بعد تموم بشه توی ربا به جای ۳۰ روز میزنه اتمام سرویس

یکی دیگه هم اینکه وقتی حجم تموم میشه حجم باقی مانده رو توی ربات منفی چند بایت نشون میده که باعث گیج شدن کاربر میشه . 
اگه منفی رو مثلا صفر نشون بده ایراد رفع میشه. 

مرسی

**Comment by Shm9220** [comment]
عکس
![Screenshot_20240318-122113_Telegram](https://github.com/TeleDark/v2ray-tel-bot/assets/130503936/eaf4f660-594c-401d-8187-cea46e28eee8)
![Screenshot_20240318-122036_Telegram](https://github.com/TeleDark/v2ray-tel-bot/assets/130503936/0fa4150f-afdd-41ec-932f-2eac315fc055)

**Comment by TeleDark** [comment]
لطفا ربات رو بروزرسانی کنید
رفع شد مشکل

**Comment by Shm9220** [comment]
آپدیت کردم ولی هنوز این دو تا مشکل هس

**Comment by TeleDark** [comment]
تلگرام ب ایدی teledark لطفا پیام بدین بررسی کنم

**Comment by TeleDark** [comment]
لطفا الان بروزرسانی کنید مشکل رفع شد

بر اساس qrcode هم میتونید اطلاعات اکانت رو دریافت کنید
